Fix/permissions
unikon-ai/unikon-stream-chat-flutter pull request #21
Opened 2024-11-25 11:05 UTC by ShashiUnikon

# Submit a pull request

## CLA

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [x] The code changes follow best practices
- [x] Code changes are tested (add some information if not applicable)

## Description of the pull request

2024-11-26 12:28 UTC, DhruvinUnikon requested changes

2024-11-26 12:28 UTC, DhruvinUnikon commented on packages/stream_chat_flutter/lib/src/attachment/file_attachment.dart
> +                          messageId: widget.message.id)
can we use async await here?

2024-11-26 12:28 UTC, DhruvinUnikon commented on packages/stream_chat_flutter/lib/src/file_downloader/file_downloader_utils.dart
> +              'Download Progress: ${(received / total * 100).toStringAsFixed(0)}%');
we have to create ui for this.

2024-11-26 12:28 UTC, DhruvinUnikon commented on packages/stream_chat_flutter/lib/src/file_downloader/file_downloader_utils.dart
> +        print('File downloaded successfully: $filePath');
print statements.

2024-11-26 12:28 UTC, DhruvinUnikon commented on packages/stream_chat_flutter/lib/src/gallery/gallery_footer.dart
> +              //   ),
remove if not required.

2024-11-26 12:28 UTC, DhruvinUnikon commented on packages/stream_chat_flutter/pubspec.yaml
> +  permission_handler: any
better if can reference the particular reference here.

2024-11-26 12:29 UTC, DhruvinUnikon commented
Just a few lines away!

2024-11-26 13:21 UTC, ShashiUnikon commented on packages/stream_chat_flutter/lib/src/gallery/gallery_footer.dart
> +              //   ),
This is stream implementation. As of now we have to hide the share button later we will uncomment this.

2024-11-26 13:21 UTC, ShashiUnikon commented on packages/stream_chat_flutter/lib/src/attachment/file_attachment.dart
> +                          messageId: widget.message.id)
Sure sir!

2024-11-26 13:28 UTC, ShashiUnikon commented on packages/stream_chat_flutter/lib/src/attachment/file_attachment.dart
> +                          messageId: widget.message.id)
Resolved

2024-11-26 13:29 UTC, ShashiUnikon commented on packages/stream_chat_flutter/pubspec.yaml
> +  permission_handler: any
I have made it due to the packages compatibility

2024-11-26 13:35 UTC, ShashiUnikon commented on packages/stream_chat_flutter/lib/src/file_downloader/file_downloader_utils.dart
> +        print('File downloaded successfully: $filePath');
Removed

2024-11-26 14:19 UTC, ShashiUnikon commented on packages/stream_chat_flutter/lib/src/file_downloader/file_downloader_utils.dart
> +    final folderUri = pref.getString('folderUri');
Make it a constant

2024-11-26 14:20 UTC, ShashiUnikon commented on packages/stream_chat_flutter/lib/src/file_downloader/file_downloader_utils.dart
> +    }
Move it at the top

2024-11-27 07:50 UTC, ShashiUnikon commented on packages/stream_chat_flutter/lib/src/file_downloader/file_downloader_utils.dart
> +    }
DOne

2024-11-27 08:00 UTC, DhruvinUnikon approved these changes
Great work!

2024-11-27 08:00 UTC, merged